<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
define( 'DUPLICATOR_AUTH_KEY', 'O]K&%0_Z;S&Rbt*FKna[:78OS(>f~+/L-|JNdk-yi.rO-X`30,X =Sc{D3d9_~Yt' );
require_once ABSPATH . 'wp-settings.php';
